-- seed: ct_ca_config (15 rows)
INSERT INTO `ct_ca_config` (`ca_name`,`gss_code`,`ca_type`,`region`,`encoding`,`col_supplier`,`col_amount`,`col_date`,`col_service`,`skip_rows`,`col_category`,`category_filter`,`notes`,`listing_url`,`cloudflare_blocked`,`updated_at`) VALUES ('Cambridgeshire and Peterborough Combined Authority','E47000008','Mayoral Strategic Authority','East of England','win1252','6','4','2','0','1','-1','','','https://cambridgeshirepeterborough-ca.gov.uk/document-library/?categoryfilter=payments-over-500','0','2026-08-19 22:13:31');
INSERT INTO `ct_ca_config` (`ca_name`,`gss_code`,`ca_type`,`region`,`encoding`,`col_supplier`,`col_amount`,`col_date`,`col_service`,`skip_rows`,`col_category`,`category_filter`,`notes`,`listing_url`,`cloudflare_blocked`,`updated_at`) VALUES ('Devon and Torbay Combined County Authority','E47000017','Strategic County Authority','South West','utf8','0','1','2','-1','1','-1','','','https://www.devonandtorbay-cca.gov.uk/transparency/','0','2026-07-06 14:14:50');
INSERT INTO `ct_ca_config` (`ca_name`,`gss_code`,`ca_type`,`region`,`encoding`,`col_supplier`,`col_amount`,`col_date`,`col_service`,`skip_rows`,`col_category`,`category_filter`,`notes`,`listing_url`,`cloudflare_blocked`,`updated_at`) VALUES ('East Midlands Combined County Authority','E47000012','Strategic Authority','East Midlands','utf8','7','6','5','4','1','-1','','','https://www.eastmidlands-cca.gov.uk/spending-over-500/','0','2026-07-06 14:14:50');
INSERT INTO `ct_ca_config` (`ca_name`,`gss_code`,`ca_type`,`region`,`encoding`,`col_supplier`,`col_amount`,`col_date`,`col_service`,`skip_rows`,`col_category`,`category_filter`,`notes`,`listing_url`,`cloudflare_blocked`,`updated_at`) VALUES ('Greater Lincolnshire Combined County Authority','E47000015','Strategic County Authority','East Midlands','utf8','15','13','10','5','1','-1','','','https://greaterlincolnshire-cca.gov.uk/transparency/transparency-1','0','2026-07-06 14:14:50');
INSERT INTO `ct_ca_config` (`ca_name`,`gss_code`,`ca_type`,`region`,`encoding`,`col_supplier`,`col_amount`,`col_date`,`col_service`,`skip_rows`,`col_category`,`category_filter`,`notes`,`listing_url`,`cloudflare_blocked`,`updated_at`) VALUES ('Greater London Authority','E12000007','Strategic Authority','London','win1252','4','8','9','11','10','-1','','',NULL,'0','2026-06-27 14:11:46');
INSERT INTO `ct_ca_config` (`ca_name`,`gss_code`,`ca_type`,`region`,`encoding`,`col_supplier`,`col_amount`,`col_date`,`col_service`,`skip_rows`,`col_category`,`category_filter`,`notes`,`listing_url`,`cloudflare_blocked`,`updated_at`) VALUES ('Greater Manchester Combined Authority','E47000001','Mayoral Strategic Authority','North West','utf8','0','5','1','3','1','-1','','','https://www.greatermanchester-ca.gov.uk/who-we-are/accounts-transparency-and-governance/transparency-reports-finance/','0','2026-07-06 14:14:50');
INSERT INTO `ct_ca_config` (`ca_name`,`gss_code`,`ca_type`,`region`,`encoding`,`col_supplier`,`col_amount`,`col_date`,`col_service`,`skip_rows`,`col_category`,`category_filter`,`notes`,`listing_url`,`cloudflare_blocked`,`updated_at`) VALUES ('Lancashire Combined County Authority','E47000016','Strategic County Authority','North West','utf8','0','1','2','-1','1','-1','','','https://lancashire-cca.gov.uk/governance/policies-and-procedures/our-publication-scheme','0','2026-07-06 14:14:50');
INSERT INTO `ct_ca_config` (`ca_name`,`gss_code`,`ca_type`,`region`,`encoding`,`col_supplier`,`col_amount`,`col_date`,`col_service`,`skip_rows`,`col_category`,`category_filter`,`notes`,`listing_url`,`cloudflare_blocked`,`updated_at`) VALUES ('Liverpool City Region Combined Authority','E47000004','Mayoral Strategic Authority','North West','utf8','0','5','1','2','1','-1','','','https://www.merseytravel.gov.uk/about/doing-business-with-merseytravel/what-merseytravel-spends/','0','2026-08-19 21:38:11');
INSERT INTO `ct_ca_config` (`ca_name`,`gss_code`,`ca_type`,`region`,`encoding`,`col_supplier`,`col_amount`,`col_date`,`col_service`,`skip_rows`,`col_category`,`category_filter`,`notes`,`listing_url`,`cloudflare_blocked`,`updated_at`) VALUES ('North East Mayoral Combined Authority','E47000011','Mayoral Strategic Authority','North East','utf8','2','8','7','0','3','-1','','','https://www.northeast-ca.gov.uk/governance/finance','0','2026-07-06 14:14:50');
INSERT INTO `ct_ca_config` (`ca_name`,`gss_code`,`ca_type`,`region`,`encoding`,`col_supplier`,`col_amount`,`col_date`,`col_service`,`skip_rows`,`col_category`,`category_filter`,`notes`,`listing_url`,`cloudflare_blocked`,`updated_at`) VALUES ('South Yorkshire Mayoral Combined Authority','E47000002','Strategic Authority','Yorkshire and the Humber','utf8','2','5','3','4','1','-1','','','https://www.southyorkshire-ca.gov.uk/Items-of-Combined-Authority-Expenditure-over-%C2%A3250','0','2026-07-06 14:14:50');
INSERT INTO `ct_ca_config` (`ca_name`,`gss_code`,`ca_type`,`region`,`encoding`,`col_supplier`,`col_amount`,`col_date`,`col_service`,`skip_rows`,`col_category`,`category_filter`,`notes`,`listing_url`,`cloudflare_blocked`,`updated_at`) VALUES ('Tees Valley Combined Authority','E47000005','Strategic Authority','North East','utf8','2','3','1','-1','1','-1','','','https://teesvalley-ca.gov.uk/about/transparency-policy-procedures/transparency/expenditure/','0','2026-07-06 14:14:50');
INSERT INTO `ct_ca_config` (`ca_name`,`gss_code`,`ca_type`,`region`,`encoding`,`col_supplier`,`col_amount`,`col_date`,`col_service`,`skip_rows`,`col_category`,`category_filter`,`notes`,`listing_url`,`cloudflare_blocked`,`updated_at`) VALUES ('West Midlands Combined Authority','E47000007','Mayoral Strategic Authority','West Midlands','utf8','4','7','6','2','2','-1','','','https://www.wmca.org.uk/what-we-do/budget-spending-and-transparency/financial-disclosures/','0','2026-08-19 22:07:15');
INSERT INTO `ct_ca_config` (`ca_name`,`gss_code`,`ca_type`,`region`,`encoding`,`col_supplier`,`col_amount`,`col_date`,`col_service`,`skip_rows`,`col_category`,`category_filter`,`notes`,`listing_url`,`cloudflare_blocked`,`updated_at`) VALUES ('West of England Combined Authority','E47000009','Mayoral Strategic Authority','South West','utf8','3','5','4','2','1','-1','','','https://www.westofengland-ca.gov.uk/about-us/democracy-funding-transparency/financial-disclosures/','0','2026-07-06 14:14:50');
INSERT INTO `ct_ca_config` (`ca_name`,`gss_code`,`ca_type`,`region`,`encoding`,`col_supplier`,`col_amount`,`col_date`,`col_service`,`skip_rows`,`col_category`,`category_filter`,`notes`,`listing_url`,`cloudflare_blocked`,`updated_at`) VALUES ('West Yorkshire Combined Authority','E47000003','Mayoral Strategic Authority','Yorkshire and the Humber','utf8','4','10','3','6','6','-1','','','https://www.westyorks-ca.gov.uk/about-us/governance-and-transparency/transparency-and-freedom-of-information/what-we-spend-and-how-we-spend-it/','0','2026-07-06 14:14:50');
INSERT INTO `ct_ca_config` (`ca_name`,`gss_code`,`ca_type`,`region`,`encoding`,`col_supplier`,`col_amount`,`col_date`,`col_service`,`skip_rows`,`col_category`,`category_filter`,`notes`,`listing_url`,`cloudflare_blocked`,`updated_at`) VALUES ('York and North Yorkshire Combined Authority','E47000014','Strategic Authority','Yorkshire and the Humber','utf8','3','8','1','10','1','-1','','','https://yorknorthyorks-ca.gov.uk/governance-and-meetings/transparency/','0','2026-07-06 14:14:50');
