-- seed: ct_supplier_service_exclusions (95 rows)
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('1','yunex','premises related','','2026-07-01 17:35:19');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('2','quadient','post service','','2026-07-01 17:40:17');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('3','quadient','mail service','','2026-07-01 17:40:17');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('4','quadient','postal','','2026-07-01 17:40:17');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('5','quadient','post handling','','2026-07-01 17:40:17');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('6','quadient','mail handling','','2026-07-01 17:40:17');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('7','quadient','mail room','','2026-07-01 17:40:17');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('8','quadient','post room','','2026-07-01 17:40:17');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('9','quadient','print room','','2026-07-01 17:40:17');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('10','quadient','reprographics','','2026-07-01 17:40:17');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('11','quadient','comms - postal','','2026-07-01 17:40:17');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('12','quadient','central postal','','2026-07-01 17:40:17');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('13','quadient','postage','','2026-07-01 17:57:21');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('14','global payments','bank charge','','2026-07-01 18:10:30');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('15','global payments','bank & credit card','','2026-07-01 18:10:30');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('16','global payments','card charge','','2026-07-01 18:10:30');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('17','global payments','card fees','','2026-07-01 18:10:30');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('18','global payments','credit\\debit card','','2026-07-01 18:10:30');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('19','global payments','credit/debit card','','2026-07-01 18:10:30');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('20','global payments','banking','','2026-07-01 18:10:30');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('21','civica','printing','','2026-07-01 18:12:17');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('22','vivedia','crematori','','2026-07-01 18:16:25');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('23','vivedia','bereavement','','2026-07-01 18:16:25');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('24','vivedia','funeral','','2026-07-01 18:16:25');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('25','vivedia','cemetery','','2026-07-01 18:16:25');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('26','vivedia','burial','','2026-07-01 18:16:25');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('27','vivedia','mortuary','','2026-07-01 18:16:25');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('28','vivedia','materials purchase','','2026-07-01 18:16:25');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('29','vivedia','goods for resale','','2026-07-01 18:16:25');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('30','vivedia','grounds','','2026-07-01 18:16:25');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('31','civica','salari','','2026-07-01 18:27:53');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('32','quadient','stationery','','2026-07-01 18:27:57');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('33','ringgo','cash collection','','2026-07-01 18:41:26');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('34','civica','indirect employee','','2026-07-01 18:54:32');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('35','worldpay','bank charge','','2026-07-01 19:17:54');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('36','worldpay','card charge','','2026-07-01 19:17:54');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('37','worldpay','banking','','2026-07-01 19:17:54');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('38','worldpay','credit card charge','','2026-07-01 19:17:54');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('39','canon uk','printing','','2026-07-01 20:23:38');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('40','canon uk','photocopying','','2026-07-01 20:23:38');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('41','canon uk','reprographics','','2026-07-01 20:23:38');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('42','canon uk','print strategy','','2026-07-01 20:23:38');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('43','tunstall','batteries','','2026-07-01 20:31:34');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('44','konica','printing','','2026-07-01 20:53:35');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('45','konica','photocopying','','2026-07-01 20:53:35');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('46','konica','photocopier','','2026-07-01 20:53:35');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('47','konica','consumable','','2026-07-01 20:53:35');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('48','konica','reprographics','','2026-07-01 20:53:35');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('49','cantium','training','','2026-07-01 21:09:30');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('50','imail comms','e-post room','','2026-07-13 21:02:50');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('51','micom technologies','e-post room','','2026-07-13 21:02:50');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('52','pitney bowes','postage','','2026-07-30 17:11:37');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('53','pitney bowes','photocopier','','2026-07-30 17:16:18');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('54','pitney bowes','office supplies','','2026-07-30 17:16:18');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('55','pitney bowes','equipment purch','','2026-07-30 17:16:18');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('56','civica','private contractor','','2026-07-30 17:53:59');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('57','civica','contract payments','','2026-07-30 18:33:54');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('58','civica','agency staff','','2026-07-30 18:33:54');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('59','civica','government grant','','2026-07-30 18:33:54');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('60','civica','revenues & benefits client','','2026-07-30 18:57:31');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('61','civica','benefits assessment','','2026-07-30 18:57:31');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('62','civica','business rates billing','','2026-07-30 18:57:31');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('63','civica','court fees','','2026-07-30 18:57:31');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('64','civica','customer call centre','','2026-07-30 18:57:31');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('65','civica','hybrid mail','','2026-07-30 19:12:10');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('66','civica','inbound mail','','2026-07-30 19:12:10');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('67','civica','print and mail','','2026-07-30 19:12:10');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('68','civica','postage','','2026-07-30 19:12:10');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('69','civica','first class','','2026-07-30 19:12:10');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('70','civica','second class','','2026-07-30 19:12:10');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('71','civica','1st & 2nd class','','2026-07-30 19:12:10');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('72','civica','special delivery','','2026-07-30 19:12:10');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('73','civica','dms hybrid','','2026-07-30 19:12:10');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('74','civica','ondemand','','2026-07-30 19:12:10');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('75','civica','offsite','','2026-07-30 19:12:10');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('76','civica','enforcement agent','','2026-07-30 19:12:10');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('77','civica','dukes','','2026-07-30 19:12:10');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('78','civica','bailiff','','2026-07-30 19:12:10');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('79','civica','civica mail','','2026-07-30 19:17:11');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('80','civica','postal service','','2026-07-30 19:17:11');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('81','civica','royal mail','','2026-07-30 19:17:11');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('82','civica','mail merge','','2026-07-30 19:17:11');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('83','civica','dms0094glo','','2026-07-30 19:17:11');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('84','zoom oxford','sen transport','','2026-08-02 21:12:51');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('85','heywood','adult care','','2026-08-02 23:56:02');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('86','heywood','early help and schools','','2026-08-02 23:56:02');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('87','cgi','strategic commissioning & partnerships','','2026-08-11 08:28:32');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('88','cgi','finance & corporate governance','','2026-08-11 08:28:32');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('89','cgi','education & lifelong learning','','2026-08-11 08:28:32');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('90','cgi','education & children','','2026-08-11 08:28:32');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('91','cgi','infrastructure & environment','','2026-08-11 08:28:32');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('92','cgi','resilient communities','','2026-08-11 08:28:32');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('93','cgi','people, performance & change','','2026-08-11 08:28:32');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('94','cgi','social work & practice','','2026-08-11 08:28:32');
INSERT INTO `ct_supplier_service_exclusions` (`id`,`supplier_pattern`,`service_keyword`,`notes`,`created_at`) VALUES ('95','cgi','adult services','','2026-08-11 08:28:32');
